version: '3'
services:
  web:
    build: ./Django
    ports:
     - "8000:8000"
    networks:
      - backend
    volumes:
      - static_volume:/web/static
      - media_volume:/web/media

  postgres:
    build: ./db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  postgres_data:
  static_volume:
  media_volume:
