version: '3'
services:
  web:
    build: ./Django
    ports:
     - "8000:8000"
    networks:
      - backend

  postgres:
    build: ./db
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  postgres-data:
    driver: local
